# Generated by Django 4.0.4 on 2022-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestemployee',
            name='request_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting')], default=('Waiting', 'Waiting'), max_length=10),
        ),
    ]
